# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKApp
  
  pod 'Alamofire', '~> 4.9.1'
  pod 'Kingfisher', '~> 5.12.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Realm', '~> 4.2.0'
  pod 'RealmSwift', '~> 4.2.0'

end
